### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by alexreg** [zeromq/czmqpp#38]
I'm creating a Portfile for MacPorts. Would you mind tagging a release, even if it's preliminary? Thanks.

@evoskuil suggests a `v1.1.0` tag for master HEAD.

**Comment by evoskuil** [comment]
+1

I'd do it but don't have permission. This tag would match the configure version.

**Comment by evoskuil** [comment]
@zeromq/core If there are no objections would you please add me as a czmq++ maintainer?

**Comment by sappo** [comment]
@evoskuil done. Give it a try.

**Comment by evoskuil** [comment]
@sappo, thanks, looks good.
