### ISSUE TITLE
FTBFS in Ubuntu 16.04

### ISSUE THREAD

**Issue by PabloCastellano** [zeromq/czmqpp#39]
```
  CXX      src/certificate.lo
In file included from ./include/czmq++/socket.hpp:45:0,
                 from ./include/czmq++/certificate.hpp:26,
                 from src/certificate.cpp:20:
./include/czmq++/socket_opt.hpp: In member function ‘int czmqpp::socket::tos()’:
./include/czmq++/socket_opt.hpp:12:29: error: ‘zsocket_tos’ was not declared in this scope
     return zsocket_tos(self_);
                             ^
./include/czmq++/socket_opt.hpp: In member function ‘int czmqpp::socket::plain_server()’:
./include/czmq++/socket_opt.hpp:15:38: error: ‘zsocket_plain_server’ was not declared in this scope
     return zsocket_plain_server(self_);

...
```
Full log here: https://paste.ubuntu.com/16002609/

**Comment by PabloCastellano** [comment]
After some debugging, for some reason when I compile czmq in Ubuntu it doesn't include these functions in the library but it does if I compile it from Debian.

README explains these functions are deprecated and they are only included if CZMQ_VERSION_MAJOR == 4

https://github.com/zeromq/czmq/blob/master/README.md#zsockopt---getset-%C3%98mq-socket-options-deprecated

However CZMQ_VERSION_MAJOR is defined to 3 in both the Debian and Ubuntu compiling environments

**Comment by evoskuil** [comment]
Hey @PabloCastellano - I'm not familiar with the particular issues. From the doc, the features are not available in v3 but are available in v4. So the deprecation must refer to a removal in future releases. In your reference to the versions on the two platforms, are you referring to versions of CZMQ that are included with the distributions? I expect if we are limited to those versions we will hit similar issues in libbitcoin-server.

**Comment by PabloCastellano** [comment]
I just realized Ubuntu 16.04 ships with libczmq3. The library in this package includes the needed functions so I'm closing this issue.
