### ISSUE TITLE
Unable to build Make error

### ISSUE THREAD

**Issue by Nevtep** [zeromq/czmqpp#5]
I'm getting this error when trying to build this lib:

Making all in src
      CXX      authenticator.lo
      CXX      certificate.lo
    authenticator.cpp: In member function 'void czmqpp::authenticator::allow(const string&)':
    authenticator.cpp:43:38: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]
         zauth_allow(self_, address.c_str());
                                          ^
    authenticator.cpp: In member function 'void czmqpp::authenticator::deny(const string&)':
    authenticator.cpp:47:37: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]
         zauth_deny(self_, address.c_str());
                                         ^
    authenticator.cpp: In member function 'void czmqpp::authenticator::configure_plain(const string&, const string&)':
    authenticator.cpp:52:47: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]
         zauth_configure_plain(self_, domain.c_str(), filename.c_str());
                                                   ^
    authenticator.cpp:52:65: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]
         zauth_configure_plain(self_, domain.c_str(), filename.c_str());
                                                                     ^
    authenticator.cpp: In member function 'void czmqpp::authenticator::configure_curve(const string&, const string&)':
    authenticator.cpp:57:47: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]
         zauth_configure_curve(self_, domain.c_str(), location.c_str());
                                                   ^
    authenticator.cpp:57:65: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]
         zauth_configure_curve(self_, domain.c_str(), location.c_str());
                                                                     ^
    In file included from ./../include/czmq++/socket.hpp:43:0,
                     from ./../include/czmq++/certificate.hpp:25,
                     from certificate.cpp:20:
    ./../include/czmq++/socket_opt.hpp: In member function 'int czmqpp::socket::tos()':
    ./../include/czmq++/socket_opt.hpp:12:29: error: 'zsocket_tos' was not declared in this scope
         return zsocket_tos(self_);
                                 ^
    ./../include/czmq++/socket_opt.hpp: In member function 'int czmqpp::socket::mechanism()':
    ./../include/czmq++/socket_opt.hpp:39:35: error: 'zsocket_mechanism' was not declared in this scope
         return zsocket_mechanism(self_);
                                       ^
    ./../include/czmq++/socket_opt.hpp: In member function 'int czmqpp::socket::immediate()':
    ./../include/czmq++/socket_opt.hpp:45:35: error: 'zsocket_immediate' was not declared in this scope
         return zsocket_immediate(self_);
                                       ^
    ./../include/czmq++/socket_opt.hpp: In member function 'void czmqpp::socket::set_tos(int)':
    ./../include/czmq++/socket_opt.hpp:129:31: error: 'zsocket_set_tos' was not declared in this scope
         zsocket_set_tos(self_, tos);
                                   ^
    ./../include/czmq++/socket_opt.hpp: In member function 'void czmqpp::socket::set_router_handover(int)':
    ./../include/czmq++/socket_opt.hpp:132:55: error: 'zsocket_set_router_handover' was not declared in this scope
         zsocket_set_router_handover(self_, router_handover);
                                                           ^
    ./../include/czmq++/socket_opt.hpp: In member function 'void czmqpp::socket::set_probe_router(int)':
    ./../include/czmq++/socket_opt.hpp:138:49: error: 'zsocket_set_probe_router' was not declared in this scope
         zsocket_set_probe_router(self_, probe_router);
                                                     ^
    certificate.cpp: In function 'zcert_t\* czmqpp::load_cert(const string&)':
    certificate.cpp:32:38: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]
         return zcert_load(filename.c_str());
                                          ^
    certificate.cpp: In member function 'void czmqpp::certificate::set_meta(const string&, const string&)':
    certificate.cpp:66:38: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]
         zcert_set_meta(self_, name.c_str(), value.c_str());
                                          ^
    certificate.cpp:66:53: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]
         zcert_set_meta(self_, name.c_str(), value.c_str());
                                                         ^
    certificate.cpp: In member function 'int czmqpp::certificate::save(const string&)':
    certificate.cpp:70:45: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]
         return zcert_save(self_, filename.c_str());
                                                 ^
    certificate.cpp: In member function 'int czmqpp::certificate::save_public(const string&)':
    certificate.cpp:74:52: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]
         return zcert_save_public(self_, filename.c_str());
                                                        ^
    certificate.cpp: In member function 'int czmqpp::certificate::save_secret(const string&)':
    certificate.cpp:78:53: error: 'zcert_save_secret' was not declared in this scope
         return zcert_save_secret(self_, filename.c_str());
                                                         ^
    make[1]: **\* [authenticator.lo] Error 1
    make[1]: **\* Waiting for unfinished jobs....
    certificate.cpp:79:1: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
    make[1]: **\* [certificate.lo] Error 1
    make: **\* [all-recursive] Error 1

**Comment by praveensmile** [comment]
In the make step, i have the following issue:
CXX      src/authenticator.lo
In file included from ./include/czmq++/authenticator.hpp:24:0,
                 from src/authenticator.cpp:20:
./include/czmq++/context.hpp:35:5: error: 'zctx_t' does not name a type
     zctx_t* self();
     ^
./include/czmq++/context.hpp:38:5: error: 'zctx_t' does not name a type
     zctx_t* self_;
     ^
src/authenticator.cpp: In constructor 'czmqpp::authenticator::authenticator(czmqpp::context&)':
src/authenticator.cpp:27:27: error: 'class czmqpp::context' has no member named 'self'
     : self_(zauth_new(ctx.self()))
                           ^
src/authenticator.cpp:27:33: error: 'zauth_new' was not declared in this scope
     : self_(zauth_new(ctx.self()))
                                 ^
src/authenticator.cpp: In destructor 'czmqpp::authenticator::~authenticator()':
src/authenticator.cpp:33:25: error: 'zauth_destroy' was not declared in this scope
     zauth_destroy(&self_);
                         ^
src/authenticator.cpp: In member function 'void czmqpp::authenticator::allow(const string&)':
src/authenticator.cpp:43:39: error: 'zauth_allow' was not declared in this scope
     zauth_allow(self_, address.c_str());
                                       ^
src/authenticator.cpp: In member function 'void czmqpp::authenticator::deny(const string&)':
src/authenticator.cpp:47:38: error: 'zauth_deny' was not declared in this scope
     zauth_deny(self_, address.c_str());
                                      ^
src/authenticator.cpp: In member function 'void czmqpp::authenticator::configure_plain(const string&, const string&)':
src/authenticator.cpp:52:66: error: 'zauth_configure_plain' was not declared in this scope
     zauth_configure_plain(self_, domain.c_str(), filename.c_str());
                                                                  ^
src/authenticator.cpp: In member function 'void czmqpp::authenticator::configure_curve(const string&, const string&)':
src/authenticator.cpp:57:66: error: 'zauth_configure_curve' was not declared in this scope
     zauth_configure_curve(self_, domain.c_str(), location.c_str());
                                                                  ^
src/authenticator.cpp: In member function 'void czmqpp::authenticator::set_verbose(bool)':
src/authenticator.cpp:61:37: error: 'zauth_set_verbose' was not declared in this scope
     zauth_set_verbose(self_, verbose);
                                     ^
make: *** [src/authenticator.lo] Error 1

How to resolve this issue?
